#ifndef FLA_NODE_H
#define FLA_NODE_H

typedef struct ASTNode ASTNode;

typedef enum {
    NODE_PROGRAM,
    NODE_MODULE,

    NODE_FUNCTION_DECLARATION,
    NODE_VARIABLE_DECLARATION,
    NODE_IF_STATEMENT,
    NODE_BREAK_STATEMENT,
    NODE_CONTINUE_STATEMENT,
    NODE_BLOCK_STATEMENT,
    NODE_WHILE_STATEMENT,
    NODE_FOR_STATEMENT,
    NODE_SWITCH_STATEMENT,

    NODE_BINARY_EXPRESSION,
    NODE_UNARY_EXPRESSION,
    NODE_TERNARY_EXPRESSION,
    NODE_COMPOUND_EXPRESSION,
    NODE_LITERAL_EXPRESSION,
    NODE_FUNCTION_CALL_EXPRESSION,
}NodeType;

#endif